/**
 * seeds/demo_tasks.js
 * -------------------
 * Reference demo/seed inspection tasks (disabled from normal application startup).
 * Use only for offline testing or manual sandbox seeding if required.
 * NOT loaded during standard application startup.
 */

module.exports = [
  // ── Authority Assigned Tasks ──
  {
    id: "LL-2026-0001",
    complaint_id: null,
    source: "authority_assigned",
    citizenId: "authority",
    citizenName: "Authority Portal",
    createdAt: "2026-09-08T09:30:00.000Z",
    status: "SUBMITTED",
    productName: "Fortune Sunlite Refined Sunflower Oil 1L",
    brand: "Adani Wilmar Ltd",
    category: "Edible Oil",
    sourceType: "Retail Supermarket",
    location: "Metro Supermarket, G.S. Road, Guwahati",
    pincode: "781005",
    issueCategory: "Net Quantity & Tare Weight Verification",
    citizenDescription: "Routine field enforcement audit scheduled by Legal Metrology Directorate.",
    citizenContact: "authority-portal@lm.gov.in",
    extractedData: {
      product_name: "Fortune Sunlite Refined Sunflower Oil",
      net_quantity: "1 L",
      mrp: "165",
    },
    aiFindings: { overallStatus: "REVIEW", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: null,
    inspectorName: null,
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0002",
    complaint_id: null,
    source: "authority_assigned",
    citizenId: "authority",
    citizenName: "Authority Portal",
    createdAt: "2026-09-07T14:15:00.000Z",
    status: "SUBMITTED",
    productName: "Tata Salt Vacuum Evaporated 1kg",
    brand: "Tata Consumer Products Ltd",
    category: "Packaged Salt",
    sourceType: "Wholesale Depot",
    location: "Bazaar India Wholesale, Beltola, Guwahati",
    pincode: "781028",
    issueCategory: "Mandatory Declarations & Packer Details",
    citizenDescription: "Special surveillance drive on packaged commodities under Rule 6(1).",
    citizenContact: "authority-portal@lm.gov.in",
    extractedData: {
      product_name: "Tata Salt Vacuum Evaporated",
      net_quantity: "1 kg",
      mrp: "28",
    },
    aiFindings: { overallStatus: "PASS", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: "INS-042",
    inspectorName: "Inspector Boruah",
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0003",
    complaint_id: null,
    source: "authority_assigned",
    citizenId: "authority",
    citizenName: "Authority Portal",
    createdAt: "2026-09-05T11:00:00.000Z",
    status: "INSPECTION_COMPLETED",
    productName: "Aashirvaad Superior MP Atta 5kg",
    brand: "ITC Limited",
    category: "Packaged Flour",
    sourceType: "Retail Store",
    location: "Reliance Smart Bazaar, Zoo Road, Guwahati",
    pincode: "781024",
    issueCategory: "Routine Annual Metrology Audit",
    citizenDescription: "Quarterly spot check on net weight compliance and consumer care helpline.",
    citizenContact: "authority-portal@lm.gov.in",
    extractedData: {
      product_name: "Aashirvaad Superior MP Atta",
      net_quantity: "5 kg",
      mrp: "260",
    },
    aiFindings: { overallStatus: "PASS", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: "COMPLIANT",
    officerDecision: "COMPLIANT",
    officerRemarks: "All statutory declarations found strictly compliant with Legal Metrology (PC) Rules, 2011.",
    inspectionDate: "2026-09-06T15:30:00.000Z",
    inspectorId: "INS-042",
    inspectorName: "Inspector Boruah",
    inspectedAt: "2026-09-06T15:30:00.000Z",
    inspectionReport: { compliant: true, verifiedAt: "2026-09-06T15:30:00.000Z" },
  },

  // ── Consumer Complaint Tasks ──
  {
    id: "LL-2026-0004",
    complaint_id: "LL-2026-0004",
    source: "consumer_complaint",
    citizenId: "CIT-001",
    citizenName: "Rahul Sharma",
    createdAt: "2026-09-09T16:45:00.000Z",
    status: "SUBMITTED",
    productName: "Patanjali Pure Honey 500g",
    brand: "Patanjali Ayurved Ltd",
    category: "Packaged Food",
    sourceType: "Retail Store",
    location: "Shree Store, Fancy Bazaar, Guwahati",
    pincode: "781001",
    issueCategory: "MRP / Price Discrepancy",
    citizenDescription: "Secondary sticker overprinted with ₹250 whereas original printed MRP shows ₹220.",
    citizenContact: "rahul.sharma@example.in",
    extractedData: {
      product_name: "Patanjali Pure Honey",
      net_quantity: "500 g",
      mrp: "220",
    },
    aiFindings: {
      overallStatus: "POTENTIAL NON-COMPLIANCE",
      declarations: [
        { field: "mrp", status: "POTENTIAL NON-COMPLIANCE", notes: "Dual pricing detected" }
      ],
    },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: null,
    inspectorName: null,
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0005",
    complaint_id: "LL-2026-0005",
    source: "consumer_complaint",
    citizenId: "CIT-002",
    citizenName: "Ananya Barua",
    createdAt: "2026-09-08T12:20:00.000Z",
    status: "SUBMITTED",
    productName: "Lay's American Style Cream & Onion",
    brand: "PepsiCo India Holdings Pvt. Ltd.",
    category: "Snack Food",
    sourceType: "Convenience Store",
    location: "Quick Mart, Six Mile, Guwahati",
    pincode: "781022",
    issueCategory: "Date of Packing Not Visible",
    citizenDescription: "Month and year of manufacture completely blurred and unreadable on back label.",
    citizenContact: "ananya.b@example.in",
    extractedData: {
      product_name: "Lay's American Style Cream & Onion",
      mrp: "20",
    },
    aiFindings: {
      overallStatus: "REVIEW",
      declarations: [
        { field: "manufacturing_or_packing_date", status: "REVIEW", notes: "Faint ink stamp" }
      ],
    },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: null,
    inspectorName: null,
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0006",
    complaint_id: "LL-2026-0006",
    source: "consumer_complaint",
    citizenId: "CIT-003",
    citizenName: "Kishore Saikia",
    createdAt: "2026-09-07T10:00:00.000Z",
    status: "INSPECTION_IN_PROGRESS",
    productName: "Britannia Good Day Butter Cookies",
    brand: "Britannia Industries Ltd",
    category: "Biscuits",
    sourceType: "Railway Stall",
    location: "Platform 1 Stall, Guwahati Railway Station",
    pincode: "781001",
    issueCategory: "Overcharging above MRP",
    citizenDescription: "Stall owner charged ₹35 for a ₹30 printed packet.",
    citizenContact: "kishore.s@example.in",
    extractedData: {
      product_name: "Britannia Good Day Butter Cookies",
      mrp: "30",
    },
    aiFindings: { overallStatus: "PASS", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "Field inspection underway at Guwahati Railway Station vendor stall.",
    inspectionDate: null,
    inspectorId: "INS-042",
    inspectorName: "Inspector Boruah",
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0007",
    complaint_id: "LL-2026-0007",
    source: "consumer_complaint",
    citizenId: "CIT-004",
    citizenName: "Bikash Kalita",
    createdAt: "2026-09-06T15:10:00.000Z",
    status: "SUBMITTED",
    productName: "Amul Taaza Homogenised Toned Milk 1L",
    brand: "Gujarat Co-operative Milk Marketing Federation",
    category: "Dairy Product",
    sourceType: "Grocery Store",
    location: "Kalita Daily Needs, Chandmari, Guwahati",
    pincode: "781003",
    issueCategory: "Net Quantity & Tare Weight Verification",
    citizenDescription: "Short delivery alleged by consumer; package appears underfilled.",
    citizenContact: "bikash.k@example.in",
    extractedData: {
      product_name: "Amul Taaza Homogenised Toned Milk",
      net_quantity: "1 L",
      mrp: "72",
    },
    aiFindings: { overallStatus: "PASS", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: null,
    inspectorName: null,
    inspectedAt: null,
    inspectionReport: null,
  },
  {
    id: "LL-2026-0008",
    complaint_id: "LL-2026-0008",
    source: "consumer_complaint",
    citizenId: "CIT-005",
    citizenName: "Meenakshi Das",
    createdAt: "2026-09-05T08:45:00.000Z",
    status: "SUBMITTED",
    productName: "Maggi 2-Minute Masala Noodles 70g",
    brand: "Nestle India Limited",
    category: "Instant Noodles",
    sourceType: "Supermarket",
    location: "City Centre Mart, Christian Basti, Guwahati",
    pincode: "781005",
    issueCategory: "Mandatory Declarations & Packer Details",
    citizenDescription: "Customer care email obscured by barcode label sticker.",
    citizenContact: "meenakshi.d@example.in",
    extractedData: {
      product_name: "Maggi 2-Minute Masala Noodles",
      net_quantity: "70 g",
      mrp: "14",
    },
    aiFindings: { overallStatus: "REVIEW", declarations: [] },
    citizenImages: [],
    inspectorImages: [],
    freshAiAnalysis: null,
    inspectionResult: null,
    officerDecision: null,
    officerRemarks: "",
    inspectionDate: null,
    inspectorId: null,
    inspectorName: null,
    inspectedAt: null,
    inspectionReport: null,
  },
];
